### ISSUE TITLE
Tasks and time are not displayed in Chrome

### ISSUE THREAD

**Issue by sorenabell** [kroman0/basecamp-calendar#1]
Tasks and time are not displayed in the diagram.
Chrome Version 43.0.2357.134

![basecamp](https://cloud.githubusercontent.com/assets/5451803/12981696/68d98a68-d0ea-11e5-9eec-cc3d9c33d48a.png)

**Comment by kroman0** [comment]
Ця версія дещо застаріла(https://en.wikipedia.org/wiki/Google_Chrome_release_history). Можливо апдейт вирішить проблему?

**Comment by kroman0** [comment]
Чи є ще проблеми з Chrome?

**Comment by sorenabell** [comment]
Після оновлення Chrome до новішої версії - нема.
